### PR TITLE
Initial commit of the .travis.yml file!

### PR DESCRIPTION
**Pull request by davidrpugh**
This PR sets up the automated CI infrastructure for the project.

### CODE REVIEW

**Comment by davidrpugh** [comment]
Useful tidbits for running [Java](https://docs.travis-ci.com/user/languages/java/) projects on Travis CI.

**Comment by herculesl** [comment]
@DavoudTaghawiNejad Can you disable the codacy checks for `distilledESL`? I am setting up everything to run through my account for all of the ESL repos...

**Comment by davidrpugh** [comment]
@DavoudTaghawiNejad Codacy is suggesting to use [JaCoCo](http://www.eclemma.org/jacoco/) to generate code coverage statistics that we can integrate with the static analysis.  Have you used this package before? Do you have alternatives?  Apparently [Cobertura](http://cobertura.github.io/cobertura/) is also supported (which I have used in the past on Java/Scala projects).

**Comment by herculesl** [comment]
@DavoudTaghawiNejad Can you take a look at the [travis logs](https://travis-ci.org/EconomicSL/destilledESL/jobs/229629063) for the build?  It would seem that maven is not finding sources to compile or tests to run.  What commands are you using to build and test via maven?

**Pull request merged**
